### PR TITLE
Migration of MCReplayEngine to vmc v2.0

### PR DESCRIPTION
**Pull request by ihrivnac**
The MCReplayEngine class is updated for the changes in TVirtualMC interface in the new vmc version

### CODE REVIEW

**Comment by ihrivnac** [comment]
@sawenzel , @benedikt-voelkel , could you, please, merge? Thank you.

**Comment by benedikt-voelkel** [comment]
Thanks @ihrivnac  I will test it later to merge it.
Also, I will then release a new tag and let you know so we can take care of that in the `alidist` recipe as well

**Comment by benedikt-voelkel** [comment]
It builds just fine @ihrivnac 
I am testing now with current G4_VMC@v6.0 and G4@v11.0

**Comment by benedikt-voelkel** [comment]
Actually, that doesn't seem to be straightforward. I have updated everything including `VGM` and `GEANT3`. However, now I have problems to build `FairRoot`.
Did you check the full build chain with the newest VMC packages and `O2`? If so, which `ROOT`, `FairRoot` did you use?

**Comment by benedikt-voelkel** [comment]
Tested with `FairRoot@master`. Logging and replay works as expected

**Comment by ihrivnac** [comment]
> Actually, that doesn't seem to be straightforward. I have updated everything including `VGM` and `GEANT3`. However, now I have problems to build `FairRoot`. Did you check the full build chain with the newest VMC packages and `O2`? If so, which `ROOT`, `FairRoot` did you use?

Yes, I tested with new vmc packages tags: 
- vmc 2.0, geant3 4.0, geant4_vmc 6.0 - dev package
- vgm - 5.0 - modified recipe
- geant4 11.0 -  dev package
- root -  not modified recipe
- FairRoot -  v18.4.1 - dev package 

I did not get compilation error due to switch to vmc 2.0,; I will check with v18.4.2, which is actually in alidist.

For the time being, there is no geant4_vmc version compatible with vmc 2.0 and geant4 10.7.px.

**Comment by benedikt-voelkel** [comment]
So the new tag `v0.5.0` contains your changes @ihrivnac

**Comment by ihrivnac** [comment]
> So the new tag `v0.5.0` contains your changes @ihrivnac

Yes, thanks. It compiles fine with the versions above; I updated also FairRoot to v18.4.2, which is the version in alidist; it requires a patch (as well as v18.4.1) in cmake/modules/FindROOT.cmake (adding  EGPythia6 in _root_dep); this may be the reason why you had to update to newer version.

**Pull request merged**
